### ISSUE TITLE
YamlのEntity設定の中にMappingが間違えてます（CouponCouponDetail.dcm.yml）

### ISSUE THREAD

**Issue by trebla-on** [EC-CUBE/coupon-plugin#46]
ec-cube 3.0.12
プラグイン：Coupon 1.0.3

問題：
ファイル： 
           app/Plugin/Coupon/Resource/doctrine/Plugin.Coupon.Entity.CouponCouponDetail.dcm.yml

対応方法：
行目：29~
```yaml
    manyToOne:
        Coupon:
            targetEntity: Plugin\Coupon\Entity\CouponCoupon
            inversedBy: CouponDetail
            joinColumn:
                name: coupon_id
                referencedColumnName: coupon_id
                nullable: false
        Product:
            targetEntity: Eccube\Entity\Product
            joinColumn:
                name: product_id
                referencedColumnName: product_id
                nullable: false
        Category:
            targetEntity: \Eccube\Entity\Category
            joinColumn:
                name: category_id
　　　　　　　　　　　　　　　　referencedColumnName: category_id
```
↓
```yaml
    manyToOne:
        Coupon:　targetEntity: Plugin\Coupon\Entity\CouponCoupon
            inversedBy: CouponDetails
            joinColumn:
                name: coupon_id
                referencedColumnName: coupon_id
            nullable: false
    manyToOne:
        Product:
            targetEntity: Eccube\Entity\Product
            joinColumn:
                name: product_id
                referencedColumnName: product_id
                nullable: false
        Category:
            targetEntity: \Eccube\Entity\Category
            joinColumn:
                name: category_id
                referencedColumnName: category_id
```
